// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "book-shop-product-service",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductsById",
        "description": "",
        "operationId": "getProductsById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "$ref": "#/definitions/String",
          "title": "Product.id"
        },
        "author": {
          "$ref": "#/definitions/String",
          "title": "Product.author"
        },
        "title": {
          "$ref": "#/definitions/String",
          "title": "Product.title"
        },
        "description": {
          "$ref": "#/definitions/String",
          "title": "Product.description"
        },
        "genre": {
          "$ref": "#/definitions/String",
          "title": "Product.genre"
        },
        "img": {
          "$ref": "#/definitions/String",
          "title": "Product.img"
        },
        "price": {
          "$ref": "#/definitions/Number",
          "title": "Product.price"
        },
        "count": {
          "$ref": "#/definitions/Number",
          "title": "Product.count"
        }
      },
      "required": [
        "id",
        "author",
        "title",
        "description",
        "genre",
        "img",
        "price",
        "count"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "NewProductPayload": {
      "title": "NewProductPayload"
    },
    "ProductDynamoSchema": {
      "title": "ProductDynamoSchema"
    },
    "Stock": {
      "properties": {
        "productId": {
          "$ref": "#/definitions/String",
          "title": "Stock.productId"
        },
        "count": {
          "$ref": "#/definitions/Number",
          "title": "Stock.count"
        }
      },
      "required": [
        "productId",
        "count"
      ],
      "additionalProperties": false,
      "title": "Stock",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "host": "6obctl4bmf.execute-api.eu-central-1.amazonaws.com"
};